name: CI - Test and Build Multi-Arch Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
         # pip install -r requirements.txt

      - name: Run unit tests
        run: |
          chmod +x ./run-unit-tests.sh
          ./run-unit-tests.sh

  build-and-publish:
    name: Build and Publish Multi-Arch Docker Image
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}/sample-api:latest
            ghcr.io/${{ github.repository }}/sample-api:${{ github.sha }}

      - name: Make Docker image public
        run: |
          ghcr_repo="ghcr.io/${{ github.repository }}/sample-api"
          token="${{ secrets.GITHUB_TOKEN }}"
          curl -X PATCH -H "Authorization: Bearer $token" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/user/packages/container/sample-api/visibility \
            -d '{"visibility":"public"}'

      - name: Post build notification
        run: echo "Docker image built and pushed successfully."
